type Champ {
    name: String!
    rarity: String!
    affinity: String!
    type: String!
    faction: String!
    race: String!
    owned: Boolean
    rating: Int
    pullCount: Int
    image: String!
}

type Query {
    allChamps: [Champ!]!
    allScores: [Score!]!
}

type Score {
    user: String!
    score: String!
    time: String!
    email: String
}