type Champ {
    name: String!
    rarity: String!
    affinity: String!
    type: String!
    faction: String!
    race: String!
    owned: Boolean
    rating: Int
    pullCount: Int
    image: String!
}

type Query {
    allChamps: [Champ!]!
}